# Generated by Django 2.2.17 on 2020-11-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='release_id',
            field=models.IntegerField(default=0),
        ),
    ]
