# Generated by Django 2.2.17 on 2020-11-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discogs', '0002_auto_20201104_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Formats',
            new_name='Format',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
    ]
